spring:
  application:
    name: mcsv-course
  datasource:
    url: ${DB_URL}
    username: ismael
    password: Test123
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}