server:
  port: 8082

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    buckets:
      customer: ${AWS_BUCKET}

spring:
  application:
    name: fl-mcsv-media
  datasource:
    url: jdbc:postgresql://localhost:5434/db-course
    username: ismael
    password: Test123
    test-on-borrow: false
    validation-query: SELECT 1 FROM dual
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
